"""Switch to 384 dim

Revision ID: 14a8421883eb
Revises: c8fa643e47c6
Create Date: 2026-09-23 22:41:50.085128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '14a8421883eb'
down_revision: Union[str, Sequence[str], None] = 'c8fa643e47c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE kb_chunks CASCADE;')
    op.alter_column('kb_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=384),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
